#!/usr/bin/env bash
# Durable setup for the dev environment: system packages, pnpm deps, local .env, schema.
# Idempotent — safe to re-run on an existing machine.
#
# Secrets never live here. Real API keys (AITUNNEL_API_KEY, APIFY_TOKEN, YOOKASSA_*,
# TELEGRAM_BOT_TOKEN) come from Cursor Cloud secrets or a local .env the developer edits.
# Without an AI key a live scrape still uses captions (local-shell), not the 48k demo.
set -euo pipefail

cd "$(dirname "$0")/.."

log() { printf '[dev-env:install] %s\n' "$*"; }

install_system_packages() {
  local wanted=()
  command -v psql >/dev/null 2>&1 || wanted+=(postgresql postgresql-contrib)
  command -v redis-server >/dev/null 2>&1 || wanted+=(redis-server)

  if [ "${#wanted[@]}" -eq 0 ]; then
    log "postgres and redis already present"
    return 0
  fi

  log "installing: ${wanted[*]}"
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${wanted[@]}"
}

install_pnpm() {
  if command -v pnpm >/dev/null 2>&1; then
    log "pnpm $(pnpm -v)"
    return 0
  fi
  log "enabling pnpm via corepack"
  corepack enable >/dev/null 2>&1 || npm install -g pnpm
}

write_local_env() {
  if [ -f .env ]; then
    log ".env already exists — leaving it alone"
    return 0
  fi

  log "writing .env with local infrastructure defaults"
  cat > .env <<'ENV'
# Generated by scripts/dev-env-install.sh — local infrastructure only, no secrets.
# Add real keys here or as Cursor Cloud secrets; see .env.example for the full list.
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/reelsfactory?schema=public"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_TELEGRAM_BOT_USERNAME="ReelsFactoryBot"
REDIS_URL="redis://localhost:6379"
REQUIRE_TELEGRAM_AUTH="false"
ENV
}

install_system_packages
install_pnpm

log "installing node dependencies"
pnpm install --frozen-lockfile

write_local_env

log "bringing services up so the schema can be pushed"
bash scripts/dev-env-start.sh

log "pushing prisma schema"
pnpm db:push

log "done"
